# Generated by Django 6.0.1 on 2026-01-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
