# Generated by Django 6.0.1 on 2026-01-31 07:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New', max_length=50, unique=True)),
                ('date_order', models.DateField(default=datetime.date.today)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('done', 'Locked'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='finance.contact')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('analytical_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.analyticalaccount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New', max_length=50, unique=True)),
                ('date_order', models.DateField(default=datetime.date.today)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('done', 'Locked'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='finance.contact')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.product')),
            ],
        ),
    ]
