# Generated by Django 6.0.1 on 2026-01-31 08:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_purchaseorder_purchaseorderline_salesorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New', max_length=50)),
                ('payment_type', models.CharField(choices=[('send', 'Send Money'), ('receive', 'Receive Money')], default='receive', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('ref', models.CharField(blank=True, max_length=100)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.contact')),
            ],
        ),
    ]
