# Generated by Django 6.0.1 on 2026-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_contact_country_contact_pincode_contact_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_residual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
